### PR TITLE
Add support for proc_pidinfo

### PR DESCRIPTION
**Pull request by akhramov**
Current implementation doesn't wrap `proc_pidinfo` function. This
function is needed for retrieving information on process, it's
threads, etc.

This change
* Adds a wrapper function for `proc_pidinfo` call.
* Adds `PIDInfo` trait to enforce the correct choice of flavors on
  type level.

### CODE REVIEW

**Comment by akhramov** [comment]
@andrewdavidmackenzie thank you so much for looking into this request!
Can I ask you to make a release once it's convenient for you?

**Comment by andrewdavidmackenzie** [comment]
Yes. BTW: I notice it won't build on 1.25.0, had to rustup to 1.26.0 to avoid this error:

```
   Compiling libproc v0.2.0 (file:///Users/andrew/workspace/libproc-rs)
error[E0658]: use of unstable library feature 'getpid': recently added (see issue #44971)
   --> src/libproc/proc_pid.rs:309:15
    |
309 |     let pid = process::id() as i32;
    |               ^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `libproc`.
```

**Comment by andrewdavidmackenzie** [comment]
Release here: https://github.com/andrewdavidmackenzie/libproc-rs/releases/tag/v0.3.0
Published in crates.io: https://crates.io/crates/libproc/0.3.0

**Comment by andrewdavidmackenzie** [comment]
README/Doc PRs are also always welcome!

Enjoy.

**Comment by akhramov** [comment]
Thank you, I really appreciate the work you have done on this library and definitely will try to help you in future.

**Comment by andrewdavidmackenzie** [comment]
BTW: would you want/like/mind being included in a list of contributors to the project?
