### ISSUE TITLE
Can't compile on rustc 1.74.1

### ISSUE THREAD

**Issue by devyn** [andrewdavidmackenzie/libproc-rs#127]
Hi,

The latest version uses `std::ptr::from_mut` (it looks like to fix a clippy warning), but that was only just stabilized in 1.76.0.

[Nushell](https://github.com/nushell/nushell) is building on 1.74 at the moment, and can't build anymore with the latest version. This is a breaking change to minimum Rust version.

See: https://github.com/nushell/nushell/pull/12182#issuecomment-1992734092

Would you please replace with something that works on 1.74, or bump major and clarify minimum rust version in Cargo.toml?

Thanks.

**Comment by andrewdavidmackenzie** [comment]
I'll fix this today.

I've never specified (or worries about much) minimum rust version...but
doing to is good I think...

I'll probably need to test it in the matrix too.

1.74 stable,.right?

**Comment by devyn** [comment]
Yes. Thanks!

**Comment by andrewdavidmackenzie** [comment]
I'm not seeing the failure in CI on 1.74.1 or locally (on macos using act).
PR (so far just added that version of rust to the matrix) [here](https://github.com/andrewdavidmackenzie/libproc-rs/pull/128)

Any ideas?

**Comment by fdncred** [comment]
These are the errors it's giving in nushell. I think `ptr_from_ref` may have been stabilized recently. 
```
error[E0658]: use of unstable library feature 'ptr_from_ref'
   --> /Users/fdncred/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libproc-0.14.5/src/libproc/proc_pid.rs:241:22
    |
241 |     let buffer_ptr = std::ptr::from_mut::<T>(&mut pidinfo).cast::<c_void>();
    |                      ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #106116 <https://github.com/rust-lang/rust/issues/106116> for more information

error[E0658]: use of unstable library feature 'ptr_from_ref'
   --> /Users/fdncred/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libproc-0.14.5/src/libproc/pid_rusage.rs:389:22
    |
389 |     let buffer_ptr = std::ptr::from_mut::<T>(&mut pidrusage).cast::<c_void>();
    |                      ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #106116 <https://github.com/rust-lang/rust/issues/106116> for more information

error[E0658]: use of unstable library feature 'ptr_from_ref'
   --> /Users/fdncred/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libproc-0.14.5/src/libproc/file_info.rs:168:22
    |
168 |     let buffer_ptr = std::ptr::from_mut::<T>(&mut pidinfo).cast::<c_void>();
    |                      ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #106116 <https://github.com/rust-lang/rust/issues/106116> for more information
```

**Comment by andrewdavidmackenzie** [comment]
Can you give some more details about where those errors are from, OS versions, rustc versions etc - as I'd like to reproduce the problem in CI before putting in place fixes for it, and controls to avoid a re-occurrance?

When I try with stable 1.74.1 on macos and linux, I do not see those failures.

thanks

**Comment by fdncred** [comment]
Sure. They're from me building [nushell](https://github.com/nushell/nushell) with `cargo install --path . --features=dataframe`

```
❯ sw_vers
ProductName:            macOS
ProductVersion:         14.4
BuildVersion:           23E214

❯ rustc --version --verbose
rustc 1.74.1 (a28077b28 2023-12-04)
binary: rustc
commit-hash: a28077b28a02b92985b3a3faecf92813155f1ea1
commit-date: 2023-12-04
host: aarch64-apple-darwin
release: 1.74.1
LLVM version: 17.0.4
```

**Comment by andrewdavidmackenzie** [comment]
OK, reproduced locally - now I need to "fix" (i.e. break) CI....

**Comment by andrewdavidmackenzie** [comment]
At last!
https://github.com/andrewdavidmackenzie/libproc-rs/actions/runs/8267240156/job/22617146403?pr=128

There was a bug in my GH Action that hid this. I will now push a fix and release later tonight.

**Comment by andrewdavidmackenzie** [comment]
Fixed and a new minor version pushed to crates.io.
https://crates.io/crates/libproc/0.14.6

I'll do the github release later tonight.

**Comment by fdncred** [comment]
Thanks so much for your help and responsiveness @andrewdavidmackenzie !!!

**Comment by devyn** [comment]
Seconded. Thank you!
